### PR TITLE
Mods should be parsed in reverse order

### PR DESCRIPTION
**Pull request by ghost**
modlist.txt lists the load order in reverse, so the code should reflect accordingly.

### CODE REVIEW

**Comment by ajventer** [comment]
When I wrote the first version I deliberately used a very short modlist - to make it easier to test, and I missed this little detail.
You are correct. I am merging this.

**Comment by jarrard** [comment]
Applied to my growing modlist.  It should be noted somewhere that the larger the modlist the longer the initial load up time. This is a FO4 engine issue, you can end up waiting as much as 2minutes before the game boots (lots of people will be tricked and close the process).

This I believe is related to the engine parsing the esp/esm. Not sure if there is a fix. (it can also be bad mod load order, use FO4Edit)

**Comment by ajventer** [comment]
That's not really a factor of movfs4l.py it would be the same if you used native mo2 on windows.
Slightly worse actually since usvfs adds a small performance hit. That's partly why Vortex chose to use symlinks. 

That said with my 2k setup using a huge modlist with dozens of high res texture mods the increase in load times have been barely noticeable.

**Comment by jarrard** [comment]
True,
It seems the MO guys might be quite against symlinks so I dunno if we can get it added in. Was thinking it be great if there was a option in the menu to select symlink mod mounting method. 

Also another side effect of symlinks is mod organizer doubles up the modlist because its designed around NOT having the files mounted until you launch. A small issue that would need to be worked around if MO ever did support symlinks.

**Comment by ajventer** [comment]
That's why I advise running UNVFS before running MO2. You want MO2 to see a pristine data directory. But I'll experiment with CIOPFS tomorrow and see how it works.

**Pull request merged**
